version: "3.9"
services:
  web:
    build: .
    command: bash -c "python etl.py"
    depends_on:
      - localstack
      - postgres
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
  postgres:
    image: fetchdocker/data-takehome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
